#!/usr/bin/env python3

import sys

from rqt_gui.main import Main


def main(argv=sys.argv):
    plugin = 'littlebot_gui_plugin'
    main = Main(filename=plugin)
    sys.exit(main.main(standalone=plugin, plugin_argument_provider=None))


if __name__ == '__main__':
    main()
